/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSigAssetsManagement } from "./MultiSigAssetsManagement";
export type { MultiSigWallet } from "./MultiSigWallet";
