/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiSigAssetsManagementSol from "./MultiSigAssetsManagement.sol";
export type { multiSigAssetsManagementSol };
import type * as multiSigVaultSol from "./MultiSigVault.sol";
export type { multiSigVaultSol };
export type { Lock } from "./Lock";
